using UnityEngine;

namespace Monopoly.Game
{
    /// <summary>
    /// References to the animated hero models, which live outside Resources. Generated by
    /// Monopoly > Rebuild Game Scene and loaded from Resources/Monopoly/HeroAssets.
    /// </summary>
    public sealed class HeroAssets : ScriptableObject
    {
        public GameObject maleHero;
        public GameObject femaleHero;
        public GameObject sword;
        public GameObject shield;
        public GameObject femaleSword;
        public GameObject femaleShield;
        /// <summary>States: Idle, Run, Victory, LevelUp, Dizzy, Hit, Die.</summary>
        public RuntimeAnimatorController controller;

        private static HeroAssets cached;

        public static HeroAssets Load()
        {
            if (cached == null) cached = Resources.Load<HeroAssets>("Monopoly/HeroAssets");
            return cached;
        }
    }
}
